language: go

go:
  - "1.15"
  - "1.16"
  - "1.17"
  - 1.18.x

go_import_path: github.com/maitredede/uadmin

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
